[package]
name         = "stg-derive"
version      = "0.0.0"
edition.workspace      = true
rust-version.workspace = true
authors.workspace      = true
publish      = false
description  = "stg 引擎编译期过程宏（Rust 强制 proc-macro 独立成 crate）"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
